"use client";
import { useState } from "react";
import Link from "next/link";

const types=[['PHONE','WhatsApp / telepon'],['BANK_ACCOUNT','Nomor rekening'],['EWALLET','E-wallet'],['DISCORD','Discord'],['FACEBOOK_NAME','Nama Facebook'],['FACEBOOK_URL','URL Facebook'],['RIOT_ID','Riot ID'],['PERSON_NAME','Nama'],['OTHER','Username lain']];
export function SubmitReportForm(){
  const [state,setState]=useState<{loading:boolean;error?:string;publicId?:string}>({loading:false});
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setState({loading:true});const form=new FormData(event.currentTarget);const response=await fetch('/api/reports',{method:'POST',body:form});const result=await response.json() as {error?:string;publicId?:string};setState(response.ok?{loading:false,publicId:result.publicId}:{loading:false,error:result.error||'Laporan gagal dikirim.'});}
  if(state.publicId)return <div className="success-state"><p className="eyebrow">{"// LAPORAN DITERIMA"}</p><h2>{state.publicId}</h2><p>Laporan masuk ke antrean moderator dan belum tampil ke publik. Anda dapat menutup halaman ini dengan aman.</p><Link className="tactical-button" href="/">KEMBALI KE BERANDA</Link></div>;
  return <form className="report-form" onSubmit={submit}>
    <fieldset><legend>01 / SUBJEK LAPORAN</legend><label>Nama profil / seller<input name="entityName" required minLength={2} maxLength={80} placeholder="Nama yang digunakan saat transaksi" /></label><div className="form-grid"><label>Jenis identifier<select name="identifierType" defaultValue="PHONE">{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Nilai identifier<input name="identifierValue" required maxLength={160} placeholder="Contoh: 0812..." /></label></div><label>Provider (opsional)<input name="provider" maxLength={40} placeholder="Contoh: BCA, DANA" /></label></fieldset>
    <fieldset><legend>02 / KRONOLOGI</legend><label>Judul kejadian<input name="title" required minLength={8} maxLength={120} /></label><label>Kronologi<textarea name="chronology" required minLength={80} maxLength={5000} rows={9} placeholder="Jelaskan urutan kejadian, kesepakatan, pembayaran, dan apa yang terjadi setelahnya." /></label><div className="form-grid"><label>Tanggal transaksi<input type="date" name="transactionDate" /></label><label>Kerugian dilaporkan (Rp)<input type="number" name="allegedLoss" min="0" step="1000" defaultValue="0" /></label></div><label>Jenis transaksi<select name="transactionType"><option value="ACCOUNT_PURCHASE">Pembelian akun</option><option value="ACCOUNT_SALE">Penjualan akun</option><option value="ACCOUNT_TRADE">Tukar akun</option><option value="MIDDLEMAN">Jasa middleman</option></select></label></fieldset>
    <fieldset><legend>03 / BUKTI PRIVAT</legend><label>Unggah bukti<input type="file" name="evidence" accept="image/png,image/jpeg,image/webp,application/pdf" multiple required /></label><p className="field-note">Maks. 5 file, 5 MB per file. PNG, JPG, WEBP, atau PDF. Bukti hanya dapat dilihat moderator/admin dan tidak otomatis dipublikasikan.</p></fieldset>
    {state.error&&<p className="form-error" role="alert">{state.error}</p>}<button className="tactical-button" disabled={state.loading}>{state.loading?'MENGIRIM...':'KIRIM UNTUK DITINJAU ↗'}</button>
  </form>;
}
