import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id:text("id").primaryKey(), email:text("email").notNull(), displayName:text("display_name").notNull(), role:text("role", { enum:["USER","VERIFIED_MIDDLEMAN","MODERATOR","ADMIN"] }).notNull().default("USER"), emailVerifiedAt:text("email_verified_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("users_email_unique").on(t.email)]);
export const entities = sqliteTable("entities", { id:integer("id").primaryKey({autoIncrement:true}), slug:text("slug").notNull().unique(), displayName:text("display_name").notNull(), description:text("description").notNull().default(""), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const identifiers = sqliteTable("identifiers", { id:integer("id").primaryKey({autoIncrement:true}), type:text("type").notNull(), rawValue:text("raw_value").notNull(), normalizedValue:text("normalized_value").notNull(), maskedValue:text("masked_value").notNull(), provider:text("provider"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("identifiers_type_normalized_unique").on(t.type,t.normalizedValue),index("identifiers_normalized_idx").on(t.normalizedValue)]);
export const entityIdentifiers = sqliteTable("entity_identifiers", { entityId:integer("entity_id").notNull().references(()=>entities.id), identifierId:integer("identifier_id").notNull().references(()=>identifiers.id), isPrimary:integer("is_primary",{mode:"boolean"}).notNull().default(false) }, (t)=>[uniqueIndex("entity_identifier_unique").on(t.entityId,t.identifierId)]);
export const reports = sqliteTable("reports", { id:integer("id").primaryKey({autoIncrement:true}), publicId:text("public_id").notNull().unique(), reporterId:text("reporter_id").notNull().references(()=>users.id), entityId:integer("entity_id").references(()=>entities.id), title:text("title").notNull(), chronology:text("chronology").notNull(), publicSummary:text("public_summary").notNull().default(""), transactionDate:text("transaction_date"), transactionValue:integer("transaction_value").notNull().default(0), allegedLoss:integer("alleged_loss").notNull().default(0), transactionType:text("transaction_type").notNull().default("ACCOUNT_PURCHASE"), status:text("status").notNull().default("SUBMITTED"), publishedAt:text("published_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t)=>[index("reports_status_idx").on(t.status),index("reports_entity_idx").on(t.entityId)]);
export const reportIdentifiers = sqliteTable("report_identifiers", { reportId:integer("report_id").notNull().references(()=>reports.id), identifierId:integer("identifier_id").notNull().references(()=>identifiers.id) }, (t)=>[uniqueIndex("report_identifier_unique").on(t.reportId,t.identifierId)]);
export const reportEvidence = sqliteTable("report_evidence", { id:integer("id").primaryKey({autoIncrement:true}), reportId:integer("report_id").notNull().references(()=>reports.id), storageKey:text("storage_key").notNull(), fileName:text("file_name").notNull(), mimeType:text("mime_type").notNull(), size:integer("size").notNull(), evidenceType:text("evidence_type").notNull().default("OTHER"), caption:text("caption").notNull().default(""), isPublicApproved:integer("is_public_approved",{mode:"boolean"}).notNull().default(false), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const reportStatusHistory = sqliteTable("report_status_history", { id:integer("id").primaryKey({autoIncrement:true}), reportId:integer("report_id").notNull().references(()=>reports.id), fromStatus:text("from_status"), toStatus:text("to_status").notNull(), actorId:text("actor_id").notNull().references(()=>users.id), note:text("note").notNull().default(""), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const moderationActions = sqliteTable("moderation_actions", { id:integer("id").primaryKey({autoIncrement:true}), reportId:integer("report_id").references(()=>reports.id), actorId:text("actor_id").notNull().references(()=>users.id), action:text("action").notNull(), rationale:text("rationale").notNull(), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const transactionConfirmations = sqliteTable("transaction_confirmations", { id:integer("id").primaryKey({autoIncrement:true}), userId:text("user_id").notNull().references(()=>users.id), entityId:integer("entity_id").notNull().references(()=>entities.id), transactionDate:text("transaction_date"), amount:integer("amount").notNull().default(0), note:text("note").notNull().default(""), status:text("status").notNull().default("PENDING"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
